import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { PrismaClient } from '@prisma-clients/project';
import { uuidv7, type AssignTaskDto, type CreateMilestoneDto, type CreateProjectDto, type CreateSiteDto, type CreateTaskDto, type CreateTaskTypeDto, type ListTasksQueryDto, type UpdateMilestoneDto, type UpdateProjectDto, type UpdateSiteDto, type UpdateTaskDto, type UpdateTaskTypeDto } from '@ipms/contracts';

@Injectable()
export class ProjectService {
  constructor(private readonly prisma: PrismaClient) {}
  async listProjects() { return this.prisma.project.findMany({ orderBy: { updatedAt: 'desc' }, include: { _count: { select: { sites: true, tasks: true } } } }); }
  async getProject(id: string) { const project = await this.prisma.project.findUnique({ where: { id }, include: { sites: { include: { region: true }, orderBy: { siteCode: 'asc' } }, taskTypes: { orderBy: { order: 'asc' } }, milestones: { include: { requirements: true }, orderBy: { sequence: 'asc' } }, _count: { select: { tasks: true } } } }); if (!project) throw new NotFoundException('Project not found'); return project; }
  /** Ordered by id, which is a uuidv7 and therefore time-ordered — Task has no createdAt column. */
  async listTasks(projectId: string, query: ListTasksQueryDto) { await this.requireProject(projectId); return this.prisma.task.findMany({ where: { projectId, ...(query.siteId ? { siteId: query.siteId } : {}), ...(query.status ? { status: query.status } : {}) }, orderBy: { id: 'desc' } }); }
  async createProject(dto: CreateProjectDto) { try { return await this.prisma.project.create({ data: { id: uuidv7(), code: dto.code, name: dto.name, clientName: dto.clientName ?? null, phase: dto.phase ?? null, startDate: dto.startDate ?? null, targetDate: dto.targetDate ?? null, defaultGeofenceRadiusM: dto.defaultGeofenceRadiusM === undefined ? 500 : dto.defaultGeofenceRadiusM, status: 'DRAFT' } }); } catch { throw new BadRequestException('Project code is already in use'); } }
  async updateProject(id: string, dto: UpdateProjectDto) { await this.requireProject(id); return this.prisma.project.update({ where: { id }, data: { ...(dto.name === undefined ? {} : { name: dto.name }), ...(dto.clientName === undefined ? {} : { clientName: dto.clientName }), ...(dto.phase === undefined ? {} : { phase: dto.phase }), ...(dto.startDate === undefined ? {} : { startDate: dto.startDate }), ...(dto.targetDate === undefined ? {} : { targetDate: dto.targetDate }), ...(dto.defaultGeofenceRadiusM === undefined ? {} : { defaultGeofenceRadiusM: dto.defaultGeofenceRadiusM }), ...(dto.status === undefined ? {} : { status: dto.status }) } }); }
  async createSite(projectId: string, dto: CreateSiteDto) { await this.requireProject(projectId); let regionId: string | null = null; if (dto.regionName) { const region = await this.prisma.region.upsert({ where: { projectId_name: { projectId, name: dto.regionName } }, update: {}, create: { id: uuidv7(), projectId, name: dto.regionName } }); regionId = region.id; } try { return await this.prisma.site.create({ data: { id: uuidv7(), projectId, regionId, siteCode: dto.siteCode, name: dto.name, latitude: dto.latitude ?? null, longitude: dto.longitude ?? null, geofenceMode: dto.geofenceMode, geofenceRadiusM: dto.geofenceRadiusM ?? null, address: dto.address ?? null, city: dto.city ?? null, area: dto.area ?? null, scopeVariant: dto.scopeVariant ?? null } }); } catch { throw new BadRequestException('Site code is already in use in this project'); } }
  async createTaskType(projectId: string, dto: CreateTaskTypeDto) { await this.requireProject(projectId); try { return await this.prisma.taskType.create({ data: { id: uuidv7(), projectId, code: dto.code, name: dto.name, category: dto.category, templateId: dto.templateId ?? null, order: dto.order ?? 0 } }); } catch { throw new BadRequestException('Task type code is already in use in this project'); } }
  async createMilestone(projectId: string, dto: CreateMilestoneDto) { await this.requireProject(projectId); const types = dto.taskTypeIds.length ? await this.prisma.taskType.count({ where: { id: { in: dto.taskTypeIds }, projectId } }) : 0; if (types !== dto.taskTypeIds.length) throw new BadRequestException('Every required task type must belong to this project'); try { return await this.prisma.$transaction(async (tx) => { const milestone = await tx.milestone.create({ data: { id: uuidv7(), projectId, code: dto.code, name: dto.name, kind: dto.kind, sequence: dto.sequence, targetDate: dto.targetDate ?? null } }); if (dto.taskTypeIds.length) await tx.milestoneRequirement.createMany({ data: dto.taskTypeIds.map((taskTypeId) => ({ milestoneId: milestone.id, taskTypeId })) }); return milestone; }); } catch (error) { if (error instanceof BadRequestException) throw error; throw new BadRequestException('Milestone code is already in use in this project'); } }
  async createTask(projectId: string, dto: CreateTaskDto, actorId: string) { await this.requireProject(projectId); const [site, taskType] = await Promise.all([this.prisma.site.findFirst({ where: { id: dto.siteId, projectId } }), this.prisma.taskType.findFirst({ where: { id: dto.taskTypeId, projectId } })]); if (!site || !taskType) throw new BadRequestException('Site and task type must belong to this project'); if (dto.origin === 'PLANNED') { const existing = await this.prisma.task.findFirst({ where: { siteId: dto.siteId, taskTypeId: dto.taskTypeId, origin: 'PLANNED' } }); if (existing) throw new BadRequestException('A planned task already exists for this site and task type'); } return this.prisma.task.create({ data: { id: uuidv7(), projectId, siteId:dto.siteId, taskTypeId:dto.taskTypeId, title:dto.title, origin:dto.origin, assigneeId:dto.assigneeId ?? null, plannedCompletionAt:dto.plannedCompletionAt ?? null, createdBy: actorId, templateId: dto.templateId ?? taskType.templateId } }); }
  async assignTask(id: string, dto: AssignTaskDto) { const task = await this.prisma.task.findUnique({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); return this.prisma.task.update({ where: { id }, data: { assigneeId: dto.assigneeId } }); }
  async updateSite(id:string,dto:UpdateSiteDto){ const site=await this.requireSite(id); let regionId:string|undefined; if(dto.regionName){ const region=await this.prisma.region.upsert({where:{projectId_name:{projectId:site.projectId,name:dto.regionName}},update:{},create:{id:uuidv7(),projectId:site.projectId,name:dto.regionName}}); regionId=region.id; } const data={...(dto.siteCode===undefined?{}:{siteCode:dto.siteCode}),...(dto.name===undefined?{}:{name:dto.name}),...(dto.latitude===undefined?{}:{latitude:dto.latitude}),...(dto.longitude===undefined?{}:{longitude:dto.longitude}),...(dto.geofenceMode===undefined?{}:{geofenceMode:dto.geofenceMode}),...(dto.geofenceRadiusM===undefined?{}:{geofenceRadiusM:dto.geofenceRadiusM}),...(dto.address===undefined?{}:{address:dto.address}),...(dto.city===undefined?{}:{city:dto.city}),...(dto.area===undefined?{}:{area:dto.area}),...(dto.scopeVariant===undefined?{}:{scopeVariant:dto.scopeVariant}),...(dto.status===undefined?{}:{status:dto.status}),...(regionId===undefined?{}:{regionId})}; try{ return await this.prisma.site.update({where:{id},data}); }catch{ throw new BadRequestException('Site code is already in use in this project'); } }
  async updateTaskType(id:string,dto:UpdateTaskTypeDto){ await this.requireTaskType(id); try{ return await this.prisma.taskType.update({where:{id},data:{...(dto.code===undefined?{}:{code:dto.code}),...(dto.name===undefined?{}:{name:dto.name}),...(dto.category===undefined?{}:{category:dto.category}),...(dto.templateId===undefined?{}:{templateId:dto.templateId}),...(dto.order===undefined?{}:{order:dto.order}),...(dto.isActive===undefined?{}:{isActive:dto.isActive})}}); }catch{ throw new BadRequestException('Task type code is already in use in this project'); } }
  async updateMilestone(id:string,dto:UpdateMilestoneDto){ const milestone=await this.requireMilestone(id); if(dto.taskTypeIds){ const found=dto.taskTypeIds.length?await this.prisma.taskType.count({where:{id:{in:dto.taskTypeIds},projectId:milestone.projectId}}):0; if(found!==dto.taskTypeIds.length) throw new BadRequestException('Every required task type must belong to this project'); } const data={...(dto.code===undefined?{}:{code:dto.code}),...(dto.name===undefined?{}:{name:dto.name}),...(dto.kind===undefined?{}:{kind:dto.kind}),...(dto.sequence===undefined?{}:{sequence:dto.sequence}),...(dto.targetDate===undefined?{}:{targetDate:dto.targetDate})}; return this.prisma.$transaction(async(tx)=>{ const saved=await tx.milestone.update({where:{id},data}); if(dto.taskTypeIds){ await tx.milestoneRequirement.deleteMany({where:{milestoneId:id}}); if(dto.taskTypeIds.length) await tx.milestoneRequirement.createMany({data:dto.taskTypeIds.map((taskTypeId)=>({milestoneId:id,taskTypeId}))}); } return saved; }); }
  /** Sets status; it does not police transitions — that is the tracking plan's Task 11. */
  async updateTask(id:string,dto:UpdateTaskDto){ await this.requireTask(id); return this.prisma.task.update({where:{id},data:{...(dto.title===undefined?{}:{title:dto.title}),...(dto.status===undefined?{}:{status:dto.status}),...(dto.assigneeId===undefined?{}:{assigneeId:dto.assigneeId}),...(dto.plannedCompletionAt===undefined?{}:{plannedCompletionAt:dto.plannedCompletionAt})}}); }
  async archiveProject(id:string){ await this.requireProject(id); return this.prisma.project.update({where:{id},data:{status:'CANCELLED'}}); }
  /** Refuses while tasks remain: the schema cascades Project to its sites, task types, milestones and tasks, so this would take the lot. */
  async deleteProject(id:string){ await this.requireProject(id); const tasks=await this.prisma.task.count({where:{projectId:id}}); if(tasks>0) throw new ConflictException(`This project still has ${tasks} task(s). Delete them, or archive the project instead.`); await this.prisma.project.delete({where:{id}}); }
  async deleteSite(id:string){ await this.requireSite(id); const tasks=await this.prisma.task.count({where:{siteId:id}}); if(tasks>0) throw new ConflictException(`This site still has ${tasks} task(s). Delete them first.`); await this.prisma.site.delete({where:{id}}); }
  /** Checked here rather than caught from Prisma's onDelete:Restrict, so the message can say which way out there is. */
  async deleteTaskType(id:string){ await this.requireTaskType(id); const tasks=await this.prisma.task.count({where:{taskTypeId:id}}); if(tasks>0) throw new ConflictException(`This task type is used by ${tasks} task(s). Deactivate it instead.`); await this.prisma.taskType.delete({where:{id}}); }
  async deleteMilestone(id:string){ await this.requireMilestone(id); await this.prisma.milestone.delete({where:{id}}); }
  async deleteTask(id:string){ const task=await this.requireTask(id); if(task.currentSubmissionId) throw new ConflictException('This task has a QC submission. Cancel the task instead of deleting it.'); await this.prisma.task.delete({where:{id}}); }
  async dashboard() { const [projects, reviewCount, rectifying] = await Promise.all([this.prisma.project.findMany({ where: { status: 'ACTIVE' }, include: { _count: { select: { sites: true } } }, take: 12, orderBy: { updatedAt: 'desc' } }), this.prisma.task.count({ where: { status: 'REVIEWING' } }), this.prisma.task.count({ where: { status: 'RECTIFYING' } })]); return { activeProjectCount: projects.length, sitesInDelivery: projects.reduce((total, p) => total + p._count.sites, 0), pendingReviews: reviewCount, rectifyingTasks: rectifying, projects }; }
  private async requireProject(id: string) { if (!await this.prisma.project.findUnique({ where: { id } })) throw new NotFoundException('Project not found'); }
  private async requireSite(id:string){ const site=await this.prisma.site.findUnique({where:{id}}); if(!site) throw new NotFoundException('Site not found'); return site; }
  private async requireTaskType(id:string){ const taskType=await this.prisma.taskType.findUnique({where:{id}}); if(!taskType) throw new NotFoundException('Task type not found'); return taskType; }
  private async requireMilestone(id:string){ const milestone=await this.prisma.milestone.findUnique({where:{id}}); if(!milestone) throw new NotFoundException('Milestone not found'); return milestone; }
  private async requireTask(id:string){ const task=await this.prisma.task.findUnique({where:{id}}); if(!task) throw new NotFoundException('Task not found'); return task; }
}
