import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import type { PrismaClient } from '@prisma-clients/project';
import { uuidv7, type AssignTaskDto, type CreateMilestoneDto, type CreateProjectDto, type CreateSiteDto, type CreateTaskDto, type CreateTaskTypeDto, type UpdateProjectDto } from '@ipms/contracts';

@Injectable()
export class ProjectService {
  constructor(private readonly prisma: PrismaClient) {}
  async listProjects() { return this.prisma.project.findMany({ orderBy: { updatedAt: 'desc' }, include: { _count: { select: { sites: true, tasks: true } } } }); }
  async getProject(id: string) { const project = await this.prisma.project.findUnique({ where: { id }, include: { sites: { include: { region: true }, orderBy: { siteCode: 'asc' } }, milestones: { include: { requirements: true }, orderBy: { sequence: 'asc' } }, _count: { select: { tasks: true } } } }); if (!project) throw new NotFoundException('Project not found'); return project; }
  async createProject(dto: CreateProjectDto) { try { return await this.prisma.project.create({ data: { id: uuidv7(), code: dto.code, name: dto.name, clientName: dto.clientName ?? null, phase: dto.phase ?? null, startDate: dto.startDate ?? null, targetDate: dto.targetDate ?? null, status: 'DRAFT' } }); } catch { throw new BadRequestException('Project code is already in use'); } }
  async updateProject(id: string, dto: UpdateProjectDto) { await this.requireProject(id); return this.prisma.project.update({ where: { id }, data: { ...(dto.name === undefined ? {} : { name: dto.name }), ...(dto.clientName === undefined ? {} : { clientName: dto.clientName }), ...(dto.phase === undefined ? {} : { phase: dto.phase }), ...(dto.startDate === undefined ? {} : { startDate: dto.startDate }), ...(dto.targetDate === undefined ? {} : { targetDate: dto.targetDate }), ...(dto.status === undefined ? {} : { status: dto.status }) } }); }
  async createSite(projectId: string, dto: CreateSiteDto) { await this.requireProject(projectId); let regionId: string | null = null; if (dto.regionName) { const region = await this.prisma.region.upsert({ where: { projectId_name: { projectId, name: dto.regionName } }, update: {}, create: { id: uuidv7(), projectId, name: dto.regionName } }); regionId = region.id; } try { return await this.prisma.site.create({ data: { id: uuidv7(), projectId, regionId, siteCode: dto.siteCode, name: dto.name, latitude: dto.latitude ?? null, longitude: dto.longitude ?? null, geofenceRadiusM: dto.geofenceRadiusM ?? 100, address: dto.address ?? null, city: dto.city ?? null, area: dto.area ?? null, scopeVariant: dto.scopeVariant ?? null } }); } catch { throw new BadRequestException('Site code is already in use in this project'); } }
  async createTaskType(projectId: string, dto: CreateTaskTypeDto) { await this.requireProject(projectId); try { return await this.prisma.taskType.create({ data: { id: uuidv7(), projectId, code: dto.code, name: dto.name, category: dto.category, templateId: dto.templateId ?? null, order: dto.order ?? 0 } }); } catch { throw new BadRequestException('Task type code is already in use in this project'); } }
  async createMilestone(projectId: string, dto: CreateMilestoneDto) { await this.requireProject(projectId); const types = dto.taskTypeIds.length ? await this.prisma.taskType.count({ where: { id: { in: dto.taskTypeIds }, projectId } }) : 0; if (types !== dto.taskTypeIds.length) throw new BadRequestException('Every required task type must belong to this project'); try { return await this.prisma.$transaction(async (tx) => { const milestone = await tx.milestone.create({ data: { id: uuidv7(), projectId, code: dto.code, name: dto.name, kind: dto.kind, sequence: dto.sequence, targetDate: dto.targetDate ?? null } }); if (dto.taskTypeIds.length) await tx.milestoneRequirement.createMany({ data: dto.taskTypeIds.map((taskTypeId) => ({ milestoneId: milestone.id, taskTypeId })) }); return milestone; }); } catch (error) { if (error instanceof BadRequestException) throw error; throw new BadRequestException('Milestone code is already in use in this project'); } }
  async createTask(projectId: string, dto: CreateTaskDto, actorId: string) { await this.requireProject(projectId); const [site, taskType] = await Promise.all([this.prisma.site.findFirst({ where: { id: dto.siteId, projectId } }), this.prisma.taskType.findFirst({ where: { id: dto.taskTypeId, projectId } })]); if (!site || !taskType) throw new BadRequestException('Site and task type must belong to this project'); if (dto.origin === 'PLANNED') { const existing = await this.prisma.task.findFirst({ where: { siteId: dto.siteId, taskTypeId: dto.taskTypeId, origin: 'PLANNED' } }); if (existing) throw new BadRequestException('A planned task already exists for this site and task type'); } return this.prisma.task.create({ data: { id: uuidv7(), projectId, siteId:dto.siteId, taskTypeId:dto.taskTypeId, title:dto.title, origin:dto.origin, assigneeId:dto.assigneeId ?? null, plannedCompletionAt:dto.plannedCompletionAt ?? null, createdBy: actorId, templateId: dto.templateId ?? taskType.templateId } }); }
  async assignTask(id: string, dto: AssignTaskDto) { const task = await this.prisma.task.findUnique({ where: { id } }); if (!task) throw new NotFoundException('Task not found'); return this.prisma.task.update({ where: { id }, data: { assigneeId: dto.assigneeId } }); }
  async dashboard() { const [projects, reviewCount, rectifying] = await Promise.all([this.prisma.project.findMany({ where: { status: 'ACTIVE' }, include: { _count: { select: { sites: true } } }, take: 12, orderBy: { updatedAt: 'desc' } }), this.prisma.task.count({ where: { status: 'REVIEWING' } }), this.prisma.task.count({ where: { status: 'RECTIFYING' } })]); return { activeProjectCount: projects.length, sitesInDelivery: projects.reduce((total, p) => total + p._count.sites, 0), pendingReviews: reviewCount, rectifyingTasks: rectifying, projects }; }
  private async requireProject(id: string) { if (!await this.prisma.project.findUnique({ where: { id } })) throw new NotFoundException('Project not found'); }
}
